#Nome do fluxo
name: CI
# é MANUAL
on:
  workflow_dispatch:
#Define os Jobs e quais são as ações.
jobs:
  first_action_job:
    runs-on: ubuntu-latest
    steps:
    - name: Imprime Hello world
      run: echo "Hello world"
    - name: Imprime Bye Bye
      run: echo "Bye Bye"
      
      
      




